# Etapa 1: Compilar TypeScript
FROM node:20-alpine AS builder

# Establece el directorio de trabajo
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./
COPY tsconfig.json ./

# Instala dependencias
RUN npm install

# Copia el código fuente (solo la carpeta src)
COPY src ./src

# Compila TypeScript a JavaScript
RUN npm run build

# Etapa 2: Imagen final para producción
FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia solo los archivos necesarios desde el builder
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

# Instala solo las dependencias de producción
RUN npm install --omit=dev

# Expone el puerto que usas en la app
EXPOSE 3000

# Comando para ejecutar la app
CMD ["node", "dist/src/server.js"]
